### PR TITLE
icon_color: updated for use in HA 0.110+

### PR DESCRIPTION
**Pull request by Mariusthvdb**
this re-instates customization of attribute icon_color in Ha 0.110

see: https://github.com/home-assistant/frontend/issues/5892

### CODE REVIEW

**Comment by bramkragten** [comment]
You should also change the source, not just the build output.

**Comment by Mariusthvdb** [comment]
thanks and I did,
please see this, about the es5.html file, do we need that after all, for the iPhone devices? https://github.com/home-assistant/frontend/issues/5892#issuecomment-631460979

**Comment by SupremeSports** [comment]
> this re-instates customization of attribute icon_color in Ha 0.110
> 
> see: [home-assistant/frontend#5892](https://github.com/home-assistant/frontend/issues/5892)

Hi, sorry to ask, but I did copy the new version of the file you updated, but still no icon colors on either of my computers nor iPhone app... Is there something I'm not doing right???

EDIT: Fixed
Making the changes in [5892](https://github.com/home-assistant/frontend/issues/5892) and [6028](https://github.com/home-assistant/frontend/issues/6028) fixed everything for me :D

```
frontend:
  extra_module_url:
    - /local/custom_ui/state-card-custom-ui.js
```

**Comment by Mariusthvdb** [comment]
check, see https://github.com/home-assistant/frontend/issues/6028#issuecomment-634502064

all fixed.

**Comment by Mariusthvdb** [comment]
update: no longer need to use the frontend: method, but load via resources:
see my [dedicated repo ](https://github.com/Mariusthvdb/custom-ui)for easy downloading and instructions

**Comment by Mariusthvdb** [comment]
HI Bram,

I was made aware that the custom card [paper-buttons-row](https://github.com/jcwillox/lovelace-paper-buttons-row) doesn't use the icon_color: setting customized by the new custom-ui card.

Maybe you changed anything in core that might have caused this? If so, could this be fixed in [my custom-ui](https://github.com/Mariusthvdb/custom-ui) card as far as you know? Or would this be an issue for the paper-buttons-row card.

Please have a look if you can find a moment?
Thanks!

**Pull request closed without merging**
